#!/bin/bash -f
#PBS -l nodes=1:ppn=8
#PBS -l walltime=72:00:00
#PBS -l mem=2048mb
#PBS -j oe

cd /home/case/fes/rh_acetate
mkdir -p /u1/scratch/case
cp rhac_bp86.inp rhac_bp86.pos /u1/scratch/case
if [ -r rhac_bp86.gbw ]; then
   /bin/cp -p rhac_bp86.gbw /u1/scratch/case
fi

cd /u1/scratch/case
/home/case/qchem/orca_3_0_1_linux_x86-64/orca rhac_bp86.inp > /home/case/fes/rh_acetate/rhac_bp86.out 
if [ -r rhac_bp86.gbw ]; then
   /bin/cp -p rhac_bp86.gbw /home/case/fes/rh_acetate
fi
if [ -r rhac_bp86.ges ]; then
   /bin/cp -p rhac_bp86.ges /home/case/fes/rh_acetate
fi
if [ -r rhac_bp86.xyz ]; then
   /bin/cp -p rhac_bp86.xyz /home/case/fes/rh_acetate
fi
/bin/rm -f rhac_bp86.gbw
/bin/rm -f rhac_bp86.ges
/bin/rm -f rhac_bp86.inp
/bin/rm -f rhac_bp86.pos
/bin/rm -f rhac_bp86.prop

